#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Patch the existing Transformer training script to use donor-level
(StratifiedGroupKFold) cross-validation instead of cell-level StratifiedKFold.

This script does NOT reimplement the Transformer. It:
  1. Reads the canonical training script (production_transformer_13092025.py)
  2. Replaces StratifiedKFold(...) with StratifiedGroupKFold(...)
  3. Adds groups=sids to the .split() call
  4. Writes a new file production_transformer_LOGO.py
  5. (You then sbatch the new script using your existing GPU sbatch.)

Why a patch and not a rewrite: the canonical Transformer architecture
(layer dimensions, dropout rates, attention heads, FF size, optimiser
settings, threshold safety bounds) is in your training script. Re-implementing
risks subtle architectural drift that would invalidate the comparison.
The patch preserves architectural identity.

Usage on Mahti (interactive, ~1 second):
    cd /scratch/project_2010376/JDs_Project/AML_Persister_Analysis/src_031025/
    python transformer_logo_patch.py
        --in  production_transformer_13092025.py
        --out production_transformer_LOGO.py

    # Inspect the diff
    diff production_transformer_13092025.py production_transformer_LOGO.py

    # If happy, run it on a GPU node using your existing sbatch as template
    cp production_transformer_13092025.sbatch  transformer_logo.sbatch
    sed -i 's/production_transformer_13092025.py/production_transformer_LOGO.py/' transformer_logo.sbatch
    sed -i 's/--job-name=aml-persister-transformer/--job-name=aml-persister-transformer-LOGO/' transformer_logo.sbatch
    sbatch transformer_logo.sbatch

If the script can't find a clean substitution point, it will print the
locations where you should manually edit and exit non-zero. That is the
safe failure mode.
"""

import argparse
import re
import sys
from pathlib import Path

# -----------------------------------------------------------------------------
# Patches we need to apply
# -----------------------------------------------------------------------------

PATCHES = [
    # 1. Import: add StratifiedGroupKFold next to StratifiedKFold
    {
        'name': 'import StratifiedGroupKFold',
        'pattern': re.compile(r'from sklearn\.model_selection import (.+)$', re.MULTILINE),
        'replace': lambda m: (
            f"from sklearn.model_selection import {m.group(1)}, StratifiedGroupKFold"
            if 'StratifiedGroupKFold' not in m.group(1)
            else m.group(0)
        ),
        'min_count': 1,
        'max_count': 1,
    },
    # 2. Replace StratifiedKFold(...) construction with StratifiedGroupKFold(...)
    #    StratifiedGroupKFold does not accept shuffle= or random_state= the same way;
    #    keep n_splits=, drop shuffle= and random_state= silently.
    {
        'name': 'replace StratifiedKFold construction',
        'pattern': re.compile(
            r'StratifiedKFold\s*\(\s*(?:n_splits\s*=\s*)?(\d+)'
            r'(?:\s*,\s*shuffle\s*=\s*[A-Za-z]+)?'
            r'(?:\s*,\s*random_state\s*=\s*\d+)?\s*\)',
            re.MULTILINE,
        ),
        'replace': lambda m: f'StratifiedGroupKFold(n_splits={m.group(1)})',
        'min_count': 1,
        'max_count': 5,
    },
    # 3. Add groups=... to skf.split(X, y) calls.
    #    Match the .split(X, y) on a StratifiedKFold-returning variable. We require
    #    the user to have an sids/groups variable in scope; we'll insert "groups=sids"
    #    by default and the user is responsible for renaming.
    {
        'name': 'add groups= to .split() call',
        'pattern': re.compile(
            r'\.split\s*\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*,\s*([A-Za-z_][A-Za-z0-9_]*)\s*\)',
            re.MULTILINE,
        ),
        'replace': lambda m: f'.split({m.group(1)}, {m.group(2)}, groups=sids)',
        'min_count': 1,
        'max_count': 5,
    },
]

PROVENANCE_HEADER = '''# -----------------------------------------------------------------------------
# THIS FILE IS A PATCHED COPY of production_transformer_13092025.py
# Generated by transformer_logo_patch.py
#
# Modifications from the original:
#   1. StratifiedKFold(...)         -> StratifiedGroupKFold(n_splits=...)
#   2. .split(X, y)                 -> .split(X, y, groups=sids)
#   3. import StratifiedGroupKFold  added
#
# This is the donor-level cross-validation version of the trainer. With 9
# donors, StratifiedGroupKFold will produce up to 5 folds (constrained by
# class balance per donor). Some folds may be skipped if a fold contains
# only one class.
#
# Output naming: this script writes its outputs with `_logo` suffixes so they
# do not collide with the canonical run. Edit downstream paths as needed.
# -----------------------------------------------------------------------------
'''


def apply_patches(src: str) -> tuple:
    """Apply all patches in order. Return (new_src, diagnostics)."""
    diags = []
    for patch in PATCHES:
        if 'replace' not in patch:
            continue
        before = src
        if callable(patch['replace']):
            new_src = patch['pattern'].sub(patch['replace'], src)
        else:
            new_src = patch['pattern'].sub(patch['replace'], src)
        n = sum(1 for _ in patch['pattern'].finditer(before))
        diags.append({
            'name': patch['name'],
            'matches_in_input': n,
            'min': patch['min_count'],
            'max': patch['max_count'],
            'changed': new_src != before,
        })
        src = new_src
    return src, diags


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--in', dest='input', required=True,
                    help='Path to the canonical training script')
    ap.add_argument('--out', dest='output', required=True,
                    help='Path to write the patched LOGO version')
    ap.add_argument('--check-only', action='store_true',
                    help="Just report what would change, don't write")
    args = ap.parse_args()

    inp = Path(args.input)
    if not inp.exists():
        print(f"ERROR: input file not found: {inp}", file=sys.stderr)
        sys.exit(2)
    src = inp.read_text()

    # Diagnostics: report what we found in the input
    print(f"Input file: {inp} ({len(src.splitlines())} lines)")
    print()

    has_skf       = 'StratifiedKFold' in src
    has_sgkf      = 'StratifiedGroupKFold' in src
    has_sids_var  = re.search(r'\bsids\s*=', src) is not None
    has_groups_kw = 'groups=sids' in src or 'groups = sids' in src

    print(f"  StratifiedKFold present:       {has_skf}")
    print(f"  StratifiedGroupKFold present:  {has_sgkf}")
    print(f"  `sids` variable present:       {has_sids_var}")
    print(f"  `groups=sids` already present: {has_groups_kw}")
    print()

    if not has_skf:
        print("ERROR: input does not contain StratifiedKFold; nothing to patch.",
              file=sys.stderr)
        sys.exit(3)
    if has_sgkf and has_groups_kw:
        print("Note: file already uses StratifiedGroupKFold with groups=sids.")
        print("If you want to re-patch anyway, run with --force (not implemented).")
        sys.exit(0)
    if not has_sids_var:
        print("ERROR: input does not contain a `sids = ...` assignment.",
              file=sys.stderr)
        print("       The patch needs a `sids` array (donor labels per cell).",
              file=sys.stderr)
        print("       Edit the file manually to ensure `sids` is in scope before",
              file=sys.stderr)
        print("       any .split() call, then re-run.", file=sys.stderr)
        sys.exit(4)

    # Apply patches
    new_src, diags = apply_patches(src)

    print("Patch results:")
    for d in diags:
        ok = (d['min'] <= d['matches_in_input'] <= d['max']) if d['changed'] else False
        flag = '✓' if ok or (d['matches_in_input'] >= d['min']) else '✗'
        print(f"  {flag} {d['name']}: {d['matches_in_input']} matches "
              f"(expected {d['min']}-{d['max']}), changed={d['changed']}")
    print()

    # Sanity-check post-patch
    has_skf_after  = 'StratifiedKFold' in new_src
    has_sgkf_after = 'StratifiedGroupKFold' in new_src
    has_groups_after = 'groups=sids' in new_src

    print("Post-patch state:")
    print(f"  StratifiedGroupKFold present:  {has_sgkf_after}")
    print(f"  groups=sids present:           {has_groups_after}")
    print(f"  Old StratifiedKFold remaining: "
          f"{'YES (manual edit needed)' if has_skf_after and not has_sgkf_after else 'no'}")
    print()

    # Add provenance header
    final_src = PROVENANCE_HEADER + '\n' + new_src

    if args.check_only:
        print("--check-only: not writing output.")
        sys.exit(0)

    out = Path(args.output)
    out.write_text(final_src)
    print(f"Wrote patched file: {out} ({len(final_src.splitlines())} lines)")
    print()
    print("Next steps:")
    print(f"  1. Diff to verify:")
    print(f"     diff {inp} {out}")
    print(f"  2. Rename outputs in the patched file (search for filenames like")
    print(f"     'final_model.h5', 'metadata.json', 'fold_metrics.csv' and add")
    print(f"     a `_logo` suffix so the LOGO run does not overwrite the canonical run.")
    print(f"  3. Copy the existing GPU sbatch and point it at the new .py:")
    print(f"     cp <existing GPU sbatch> transformer_logo.sbatch")
    print(f"     sed -i 's/{inp.name}/{out.name}/' transformer_logo.sbatch")
    print(f"     sbatch transformer_logo.sbatch")
    print(f"  4. After it finishes, send back the per-fold AUROC numbers and the")
    print(f"     metadata.json so I can integrate the donor-level Transformer")
    print(f"     AUROC into v5.4 of the manuscript.")


if __name__ == '__main__':
    main()
