#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Transformer LOGO patch — v2 (line-targeted).

The previous regex-based patch over-matched the `.split(X, y)` pattern: it
would have added `groups=sids` to three call sites, but only one of those
is a StratifiedKFold call. The other two are a held-out
StratifiedShuffleSplit and a GroupShuffleSplit, neither of which should
receive a fresh `groups=sids` from this patch.

This v2 patch makes only the minimum-necessary edits at known line numbers
(verified against `production_transformer_13092025.py` from the project
repository: lines 21, 266, 270 in the canonical 587-line file). It will
refuse to run if the input file does not match the expected layout.

Three changes:
  Line 21:  add StratifiedGroupKFold to the sklearn import
  Line 266: StratifiedKFold(n_splits=n_folds, shuffle=True, random_state=SEED)
            -> StratifiedGroupKFold(n_splits=n_folds)
  Line 270: skf.split(X, y)
            -> skf.split(X, y, groups=sids)

Lines 457 (held-out test) and 505 (val_split inside the training fold) are
INTENTIONALLY LEFT ALONE.

Usage:
    python transformer_logo_patch_v2.py \\
        --in  ../production_transformer_13092025.py \\
        --out production_transformer_LOGO_25042026.py \\
        --check-only

Then if happy:
    python transformer_logo_patch_v2.py \\
        --in  ../production_transformer_13092025.py \\
        --out production_transformer_LOGO_25042026.py
"""

import argparse
import sys
from pathlib import Path


# ---- Expected anchors (line numbers + content fragments) --------------------
EXPECTED_IMPORT_LINE = 21
EXPECTED_IMPORT_CONTAINS = "from sklearn.model_selection import StratifiedKFold"

EXPECTED_SKF_CTOR_LINE = 266
EXPECTED_SKF_CTOR_CONTAINS = "StratifiedKFold(n_splits=n_folds, shuffle=True, random_state=SEED)"

EXPECTED_SKF_SPLIT_LINE = 270
EXPECTED_SKF_SPLIT_CONTAINS = "skf.split(X, y)"


# ---- Replacements ------------------------------------------------------------
def patch_import(line: str) -> str:
    """Add StratifiedGroupKFold to the sklearn.model_selection import."""
    if "StratifiedGroupKFold" in line:
        return line
    return line.replace(
        "from sklearn.model_selection import StratifiedKFold",
        "from sklearn.model_selection import StratifiedKFold, StratifiedGroupKFold",
    )

def patch_ctor(line: str) -> str:
    """StratifiedKFold(n_splits=n_folds, shuffle=True, random_state=SEED)
       -> StratifiedGroupKFold(n_splits=n_folds)
       Note: StratifiedGroupKFold does not accept shuffle= or random_state= the
       same way; we drop those to keep the call signature valid.
    """
    return line.replace(
        "StratifiedKFold(n_splits=n_folds, shuffle=True, random_state=SEED)",
        "StratifiedGroupKFold(n_splits=n_folds)",
    )

def patch_split(line: str) -> str:
    """skf.split(X, y) -> skf.split(X, y, groups=sids)"""
    if "groups=" in line:
        return line
    return line.replace(
        "skf.split(X, y)",
        "skf.split(X, y, groups=sids)",
    )


PROVENANCE = """# -----------------------------------------------------------------------------
# THIS FILE IS A PATCHED COPY of production_transformer_13092025.py
# Generated by transformer_logo_patch_v2.py on user request.
#
# THREE LINE-TARGETED MODIFICATIONS:
#   Line 21:  added StratifiedGroupKFold to sklearn import
#   Line 266: StratifiedKFold(...)        -> StratifiedGroupKFold(n_splits=n_folds)
#   Line 270: skf.split(X, y)             -> skf.split(X, y, groups=sids)
#
# Held-out StratifiedShuffleSplit (line ~457) and val GroupShuffleSplit
# (line ~505) are LEFT UNCHANGED.
#
# OUTPUT FILES MUST BE RENAMED before running, to avoid clobbering the
# canonical run. See README.
# -----------------------------------------------------------------------------
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--in', dest='input', required=True)
    ap.add_argument('--out', dest='output', required=True)
    ap.add_argument('--check-only', action='store_true')
    args = ap.parse_args()

    inp = Path(args.input)
    if not inp.exists():
        print(f"ERROR: input not found: {inp}", file=sys.stderr); sys.exit(2)

    src_lines = inp.read_text().splitlines(keepends=True)
    n_lines = len(src_lines)
    print(f"Input: {inp} ({n_lines} lines)")
    print()

    # Verify expected anchors
    issues = []
    def check_anchor(idx_1based, expected_substr, label):
        if idx_1based - 1 >= n_lines:
            issues.append(f"  ✗ {label}: line {idx_1based} does not exist (file has {n_lines} lines)")
            return False
        actual = src_lines[idx_1based - 1].rstrip()
        ok = expected_substr in actual
        flag = "✓" if ok else "✗"
        print(f"  {flag} {label}: line {idx_1based}")
        print(f"      expected substring: {expected_substr!r}")
        print(f"      actual line:        {actual!r}")
        if not ok:
            issues.append(f"  ✗ {label}: line {idx_1based} did not match")
        return ok

    print("Anchor verification:")
    ok_imp   = check_anchor(EXPECTED_IMPORT_LINE,    EXPECTED_IMPORT_CONTAINS,    "sklearn import")
    ok_ctor  = check_anchor(EXPECTED_SKF_CTOR_LINE,  EXPECTED_SKF_CTOR_CONTAINS,  "StratifiedKFold ctor")
    ok_split = check_anchor(EXPECTED_SKF_SPLIT_LINE, EXPECTED_SKF_SPLIT_CONTAINS, "skf.split call")
    print()

    if not (ok_imp and ok_ctor and ok_split):
        print("ABORT: anchors did not match the expected file layout.", file=sys.stderr)
        print("       Either the file has been edited, or the line numbers shifted.",
              file=sys.stderr)
        print("       Show me the actual lines (grep output) and I'll update the patch.",
              file=sys.stderr)
        sys.exit(3)

    # Apply patches
    new_lines = src_lines.copy()
    new_lines[EXPECTED_IMPORT_LINE - 1]    = patch_import(new_lines[EXPECTED_IMPORT_LINE - 1])
    new_lines[EXPECTED_SKF_CTOR_LINE - 1]  = patch_ctor(  new_lines[EXPECTED_SKF_CTOR_LINE - 1])
    new_lines[EXPECTED_SKF_SPLIT_LINE - 1] = patch_split( new_lines[EXPECTED_SKF_SPLIT_LINE - 1])

    print("Post-patch lines:")
    print(f"  Line {EXPECTED_IMPORT_LINE}:    {new_lines[EXPECTED_IMPORT_LINE - 1].rstrip()!r}")
    print(f"  Line {EXPECTED_SKF_CTOR_LINE}:  {new_lines[EXPECTED_SKF_CTOR_LINE - 1].rstrip()!r}")
    print(f"  Line {EXPECTED_SKF_SPLIT_LINE}: {new_lines[EXPECTED_SKF_SPLIT_LINE - 1].rstrip()!r}")
    print()

    # Sanity: lines 457 and 505 must NOT have changed
    for ln in (457, 505):
        if ln - 1 < n_lines and new_lines[ln - 1] != src_lines[ln - 1]:
            print(f"ERROR: line {ln} changed but should not have. Aborting.", file=sys.stderr)
            sys.exit(4)
    print("Confirmed: held-out split (line 457) and val GroupShuffleSplit (line 505) UNCHANGED.")
    print()

    if args.check_only:
        print("--check-only: not writing output.")
        sys.exit(0)

    # Write
    final = PROVENANCE + "".join(new_lines)
    out = Path(args.output)
    out.write_text(final)
    print(f"Wrote: {out}")
    print()
    print("Next steps:")
    print(f"  1. Diff:  diff {inp} {out} | head -40")
    print(f"  2. RENAME OUTPUT FILES inside {out.name} so the LOGO run does not")
    print(f"     overwrite the canonical run's results. Use sed:")
    print(f"     sed -i 's/final_model\\.h5/final_model_logo.h5/g' {out}")
    print(f"     sed -i 's/best_model\\.h5/best_model_logo.h5/g' {out}")
    print(f"     sed -i 's/metadata\\.json/metadata_logo.json/g' {out}")
    print(f"     sed -i 's/fold_metrics\\.csv/fold_metrics_logo.csv/g' {out}")
    print(f"     sed -i 's/pca\\.pkl/pca_logo.pkl/g' {out}")
    print(f"     sed -i 's|results/models|results/models_logo|g' {out}")
    print(f"     sed -i 's|results/metadata|results/metadata_logo|g' {out}")
    print(f"  3. Verify renaming:")
    print(f"     grep -n 'results/models\\|results/metadata\\|\\.h5\\|metadata\\.json\\|fold_metrics\\.csv' {out}")
    print(f"  4. Make sure the output directories exist:")
    print(f"     mkdir -p results/models_logo results/metadata_logo")
    print(f"  5. Edit n_folds to 3 (because we only have 9 donors, 6 positive / 3 negative;")
    print(f"     5-fold StratifiedGroupKFold cannot be satisfied — see baselines_logo.py output).")
    print(f"     Search for `n_folds = 5` (or wherever it is set) in {out} and change to `n_folds = 3`.")
    print(f"  6. Submit on a GPU node using a copy of your existing training sbatch.")


if __name__ == '__main__':
    main()